version: '3.1'

services:
  database:
    image: postgres
    restart: never
    environment:
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: security_keycloak
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/
    ports:
      - '5431:5432'
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: database
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: security_keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: admin1234
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    ports:
      - 8080:8080
      - 8443:8443
    command:
      - start-dev      
    depends_on:
      - database